# Generated by Django 3.1.6 on 2021-03-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.CharField(default='Old Dojo', max_length=255),
            preserve_default=False,
        ),
    ]
